### ISSUE TITLE
500 Error on Refresh

### ISSUE THREAD

**Issue by mikebski** [nuvolo/sincronia#204] opened 2021-06-21 13:56 UTC
I'm getting a 500 error when refreshing:

Server version: 1.1.2

package.json 

```
"devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.14.5",
    "@babel/preset-env": "^7.14.5",
    "@babel/preset-typescript": "^7.14.5",
    "@nuvolo/servicenow-types": "^0.2.1-alpha.1",
    "@sincronia/babel-plugin": "^0.4.2-alpha.3",
    "@sincronia/babel-plugin-remove-modules": "^0.4.2-alpha.3",
    "@sincronia/babel-preset-servicenow": "^0.4.2-alpha.3",
    "@sincronia/core": "^0.4.2-alpha.4",
    "@sincronia/typescript-plugin": "^0.4.2-alpha.3",
    "corejs": "^1.0.0"
  },
```

Server side error:

```
The undefined value has no properties.: com.glide.rest.domain.ServiceException: The undefined value has no properties.: com.glide.rest.service.custom.CustomServiceExceptionResolver.throwServiceException(CustomServiceExceptionResolver.java:82)
com.glide.rest.service.custom.CustomServiceExceptionResolver.throwServiceException(CustomServiceExceptionResolver.java:77)
com.glide.rest.service.custom.CustomServiceExceptionResolver.resolveForException(CustomServiceExceptionResolver.java:45)
com.glide.rest.service.custom.CustomServiceResultHandler.handle(CustomServiceResultHandler.java:22)
com.glide.rest.service.custom.CustomService.execute(CustomService.java:84)
com.glide.rest.handler.impl.ServiceHandlerImpl.invokeService(ServiceHandlerImpl.java:37)
com.glide.rest.processors.RESTAPIProcessor.process(RESTAPIProcessor.java:287)
com.glide.processors.AProcessor.runProcessor(AProcessor.java:596)
com.glide.processors.AProcessor.processTransaction(AProcessor.java:266)
com.glide.processors.ProcessorRegistry.process0(ProcessorRegistry.java:181)
com.glide.processors.ProcessorRegistry.process(ProcessorRegistry.java:169)
com.glide.ui.GlideServletTransaction.process(GlideServletTransaction.java:44)
com.glide.sys.Transaction.run(Transaction.java:2275)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

**Comment by mikebski** [comment] 2021-06-21 15:34
I just created a new sincronia project locally and installed the libs with NPM from scratch and am getting the same error - I'm also getting this error in multiple projects - it's a blocker now because I can't pull any new files from SN...

**Comment by mikebski** [comment] 2021-06-21 16:08
Debugging this - I run this in a script in SN:

```
var utils = new SincUtils();
var body = {
  "includes": {
    "content_css": {
      "style": {
        "type": "css"
      }
    }
  },
  "excludes": {
    "sys_scope_privilege": true,
    "sys_dictionary": true,
    "sys_impex_entry": true,
    "sys_security_acl": true,
    "sys_transform_map": true,
    "sys_ui_policy": true,
    "sys_ui_list_control": true,
    "sys_relationship": true,
    "sys_report": true,
    "item_option_new": true,
    "sys_process_flow": true,
    "content_block_programmatic": true,
    "sp_instance": true,
    "sys_transform_script": true,
    "sc_category": true,
    "sysrule_view": true,
    "sc_cat_item": true,
    "sysevent_in_email_action": true,
    "sys_navigator": true,
    "sys_transform_entry": true,
    "metric_definition": true,
    "content_block_lists": true,
    "content_block_detail": true,
    "sp_portal": true,
    "sc_cat_item_producer": true,
    "sys_impex_map": true
  },
  "tableOptions": {},
  "withFiles": true
}	
	


utils.getManifest({
    scopeName: "myscope",
    includes: body.includes,
    excludes: body.excludes,
    tableOptions: body.tableOptions
  });
```

I get error:

![image](https://user-images.githubusercontent.com/4280588/122793533-53032680-d289-11eb-8d34-0d4744e4b092.png)

It's in SincUtils:

![image](https://user-images.githubusercontent.com/4280588/122793597-63b39c80-d289-11eb-96b2-5aaf12b6ea66.png)

**Comment by mikebski** [comment] 2021-06-23 12:29
@bbarber9 

It appears that `this` in the `SincUtils.buildTableMap` method is undefined. See the debug statement here:

```
      {
        key: "buildTableMap",
        value: function buildTableMap(config) {
          var tableName = config.tableName,
            scopeId = config.scopeId,
            getContents = config.getContents,
            includes = config.includes,
            excludes = config.excludes,
            tableOptions = config.tableOptions;
          var results = {
            records: {}
          };
			gs.addInfoMessage("Tablename: " + tableName + " this: " + this);
          var fieldListForTable = this.getFileMap({
            tableName: tableName,
            includes: includes,
            excludes: excludes
          });
```

Here's the output from running that:

![image](https://user-images.githubusercontent.com/4280588/123096375-08a2b680-d3fd-11eb-885a-4b847111aa27.png)

I have re-installed from the git repo's latest code, so something funky is going on here. Any ideas?

**Comment by mikebski** [comment] 2021-06-24 11:38
This seems to be a larger problem, and I think it's due to some service now setting.

In my transpiled scripts, some methods have "this" undefined inside them - I can't figure out why, but it's causing lots of problems. I have scripts that have not changed in several months and they are suddenly not working because of this.

It's not just Sincronia, curious to hear if there's a fix other than converting.

**Comment by bbarber9** [comment] 2021-06-24 17:24
@mikebski I moved on from Nuvolo and the SN space. I reached out to one of my contacts at Nuvolo who will hopefully get you sorted out :+1:

**Comment by brandonsmith-nuvolo** [comment] 2021-07-14 02:26
@mikebski This is a larger issue with ServiceNow that we are also working through. It has to do with how SN scripts are processed. I am looking into it but best guess right now is that it is how Script Includes are formatted as output from Sincronia. 

The workaround as of now is to flip this property off, which is added as a global change ServiceNow has made with how Script Includes are executed. 

com.glide.script.interpret.short.expressions

**Comment by brandonsmith-nuvolo** [comment] 2021-07-27 18:22
Hi @mikebski !

We are close to implementing a fix for this issue. As said before, the issue is seen when ServiceNow makes a change at the instance level of how scripts run. In compiled mode, the "use strict" at the top of each file is not handled, meaning that the rhino engine doesn't use it. In interpreted mode, which is the mode that ServiceNow is switching customers to, the "use strict" is being used by the Rhino engine and thus causing the error you see from Sincronia. 

We are working a solution in two ways: 
1. We are updating Sincronia to not place "use strict" in any file transpiled by babel into ServiceNow (https://github.com/nuvolo/sincronia/pull/206)
2. We are updating the Sincronia scoped application to remove the "use strict" from the file. This will resolve the 500 error that you have seen. 

Thanks!
Brandon

**Comment by brandonsmith-nuvolo** [comment] 2021-08-02 19:10
Hi @mikebski!

We have released an updated version of the Sincronia Scoped Application which should resolve your issue. You should be able to upgrade it now to version 1.1.3. Please see the tagged version here: https://github.com/nuvolo/sincronia-server-scoped-app/releases/tag/1.1.3

Additionally, we merged in the PR mentioned in my last post to resolve other "use strict" errors has been merged, tagged, and deployed. If you are using the Sincronia Babel package for transpiling your typescript files, you can upgrade your version of https://github.com/nuvolo/sincronia/tree/dev/packages/babel-preset-servicenow to 0.4.2-alpha.6 and it will properly remove "use strict" from the top of all files. If you are using the typescript compiler, you should be able to update your properties in your tsconfig to not use strict mode. 

These changes should resolve this issue fully. Please let me know if you have more issues with it!
Brandon

**Closed as completed by brandonsmith-nuvolo** 2021-08-02 19:10 UTC
